services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    ports:
      - "31521:1521"
    environment:
      - ORACLE_PWD=Oracle_123
    volumes:
      - ./init-scripts:/opt/hr
      - oracle_data:/opt/oracle/oradata  # This is the persistent volume
    shm_size: '1g'

volumes:
  oracle_data:
